name: Build Homebrew
# Builds and tests Storm's homebrew installation

on:
  # needed to trigger the workflow manually
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

env:
  # GitHub runners currently have 4 cores
  NR_JOBS: "4"

jobs:
  # Build Homebrew formula
  build:
    name: Build Tests (${{ matrix.config.name }}, ${{ matrix.config.buildType }})
    strategy:
      matrix:
        config:
          - {name: "macOS 14, ARM",
             distro: "macos-14",
             buildType: "Release"
            }
          - {name: "macOS 15, ARM",
             distro: "macos-15",
             buildType: "Release"
            }
          - {name: "macOS 15, Intel",
             distro: "macos-15-intel",
             buildType: "Release"
            }
          - {name: "macOS 26, ARM",
             distro: "macos-26",
             buildType: "Release"
            }
          - {name: "macOS 26, Intel",
             distro: "macos-26-intel",
             buildType: "Release"
            }
    runs-on: ${{ matrix.config.distro }}
    steps:
      - name: Git clone
        uses: actions/checkout@v6
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@main

      - name: Audit formula
        run: brew audit --strict --new --online stormchecker
      - name: Build Storm from Homebrew formula
        run: brew install -v --build-from-source stormchecker

      # Test installation of Storm
      - name: Run test
        run: brew test stormchecker
      - name: Run Storm
        run: storm --version

      # Test by building starter project
      - name: Checkout starter project
        uses: actions/checkout@v6
        with:
          repository: stormchecker/storm-project-starter-cpp
          path: storm-starter
      - name: Build starter project
        working-directory: ./storm-starter
        run: |
          mkdir build
          cd build
          cmake -DNEVER_FETCH_STORM=TRUE ..
          make -j "${NR_JOBS}"
      - name: Run starter project
        working-directory: ./storm-starter
        run: ./build/bin/starter-project examples/die.pm examples/die.pctl
